### PR TITLE
Flexfix only PR

### PR DESCRIPTION
**Pull request by futtta**
As requested by @damienmckenna in issue (https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/issues/26#issuecomment-221918492).

### CODE REVIEW

**Comment by futtta** [comment]
not the git(hub)-expert, so lots of reverts + juggling spaces & tabs to have the smallest diff possible, hope all is OK this way.

**Comment by glensc** [comment]
superseded by #32, @tubalmartin please merge #32
@futtta plz close this one

**Comment by futtta** [comment]
@glensc there's more in this then just #30

**Comment by glensc** [comment]
@futtta no it's not:
https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/pull/30/files

you reverted all other changes.

and anyway you should make 1 PR per 1 feature/fix.

plus i added test for your changes in #30

**Comment by futtta** [comment]
who'd have thunk, you're right! ;-)

**Comment by glensc** [comment]
thunk? you mean 'thought'?

**Comment by futtta** [comment]
[just kidding](http://www.urbandictionary.com/define.php?term=Who%20would%27ve%20thunk%3F) @glensc ;-)

**Pull request closed without merging**
