### PR TITLE
Never change memory_limit = -1 or max_execution_time = 0

### PR DESCRIPTION
**Pull request by ajpevers**
Fixes https://github.com/magento/magento2/issues/2461
Replaces https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/pull/28
Replaces https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/pull/31

### CODE REVIEW

**Comment by ajpevers** [comment]
Hello @tubalmartin,

It would be greatly appreciated if you would approve this pull request soon, as the https://github.com/magento/magento2 project depends on it. You would help the Magento 2 community a great deal.

Fixes https://github.com/magento/magento2/issues/2461

Thank you!

**Comment by ajpevers** [comment]
I have tested this in a Magento 2 project that consistently produced errors because of this bug. Now it runs without errors.

**Comment by tubalmartin** [comment]
Thank you for the MR!

**Comment by ajpevers** [comment]
Whow, that is FAST! Thanks @tubalmartin

**Pull request merged**
